/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Course Overview',
    },
    {
      type: 'category',
      label: 'Module 1: ROS 2 Fundamentals',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '01-ros2-fundamentals',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 2: Physics Simulation',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '02-physics-simulation',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 3: NVIDIA Isaac Sim',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '03-isaac-sim',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 4: VLA & Autonomy',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '04-vla-autonomy',
        },
      ],
    },
  ],
};

export default sidebars;
